/* ============================== EXPLOSION ============================== */

DROP TABLE user_user CASCADE CONSTRAINTS;

DROP TABLE guest_property CASCADE CONSTRAINTS;

DROP TABLE staff_maintenance_task CASCADE CONSTRAINTS;

DROP TABLE amenity_payment CASCADE CONSTRAINTS;

DROP TABLE room_amenity CASCADE CONSTRAINTS;

DROP TABLE property_amenity CASCADE CONSTRAINTS;

DROP TABLE guest_amenity CASCADE CONSTRAINTS;

DROP TABLE host_amenity CASCADE CONSTRAINTS;

DROP TABLE host_policy CASCADE CONSTRAINTS;

DROP TABLE occupancy_report_cancellation CASCADE CONSTRAINTS;

DROP TABLE room_policy CASCADE CONSTRAINTS;

DROP TABLE guest_policy CASCADE CONSTRAINTS;

DROP TABLE property_policy CASCADE CONSTRAINTS;

DROP TABLE host_staff_role CASCADE CONSTRAINTS;

DROP TABLE occupancy_report_booking CASCADE CONSTRAINTS;



/* ============================== ENTITY ============================== */

DROP TABLE maintenance_task CASCADE CONSTRAINTS;

DROP TABLE maintenance_request CASCADE CONSTRAINTS;

DROP TABLE review CASCADE CONSTRAINTS;

DROP TABLE receipt CASCADE CONSTRAINTS;

DROP TABLE refund CASCADE CONSTRAINTS;

DROP TABLE cancellation CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE invoice CASCADE CONSTRAINTS;

DROP TABLE occupancy_report CASCADE CONSTRAINTS;

DROP TABLE booking CASCADE CONSTRAINTS;

DROP TABLE payout CASCADE CONSTRAINTS;

DROP TABLE earning CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

DROP TABLE room CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE guest CASCADE CONSTRAINTS;

DROP TABLE host CASCADE CONSTRAINTS;

DROP TABLE "user" CASCADE CONSTRAINTS;

DROP TABLE policy CASCADE CONSTRAINTS;

DROP TABLE amenity CASCADE CONSTRAINTS;

DROP TABLE property_type CASCADE CONSTRAINTS;

DROP TABLE staff_role CASCADE CONSTRAINTS;
